# Generated by Django 4.2.5 on 2023-09-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('starter', 'starter'), ('main_course', 'main_course'), ('dessert', 'dessert'), ('Gin', 'Gin'), ('Whisky', 'Whisky'), ('Vodka', 'Vodka')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Drinks', 'Drinks')], max_length=120, null=True),
        ),
    ]
