# Generated by Django 4.2.5 on 2023-09-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_course_name_alter_meal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='food_default.webp', upload_to='food_pics'),
        ),
    ]
