# Generated by Django 4.2.5 on 2023-09-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='/media/food.jpg', upload_to='food_pics/'),
        ),
    ]
