# Generated by Django 4.2.5 on 2023-09-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_food_created_food_update_alter_food_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='food',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
