# Generated by Django 4.2.5 on 2023-09-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'cart'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Cartitem'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'course'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('-created',), 'verbose_name': 'food'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'meal'},
        ),
    ]
